# https://gist.github.com/gnarf/b103e77f37236ca72d8e
:vms:
  nfs-master1:
    :hostname: "nfs-master1"
    :ip: "192.168.50.101"
    :ram: 2048
    :cpu: 2
    :box: "ubuntu/xenial64"
    :id: 10

  nfs-worker1:
    :hostname: "nfs-worker1"
    :ip: "192.168.50.102"
    :ram: 2048
    :cpu: 2
    :box: "ubuntu/xenial64"
    :id: 11

:groups:
  nfs-master1:
    - nfs-master1
  slaves:
    - nfs-worker1
  agents:
    - nfs-worker1
  servers:
    - nfs-master1
    - nfs-worker1
  kubernetes-nfs-master1:
    - nfs-master1
  kubernetes-workers:
    - nfs-worker1
  kubernetes:
    - nfs-master1
    - nfs-worker1
