---
##############################################################################
# SERVERS: Install and configure ntp
##############################################################################
- hosts: servers
  name: servers install etckeeper
  gather_facts: True
  become: yes
  become_method: sudo
  environment:
    DEBIAN_FRONTEND: noninteractive
  tags:
    - servers
    - install
    - servers_install
    - etckeeper
  roles:
    - role: boss-ansible-role-etckeeper
    - role: boss-ansible-role-tools
      task: tools
      bossjones__user: vagrant
      bossjones__group: vagrant

- hosts: masters
  name: (masters) - Install and configure nfs
  gather_facts: True
  become: yes
  become_method: sudo
  environment:
    DEBIAN_FRONTEND: noninteractive
  vars:
    boss__ntp__timezone: 'America/New_York'
  tags:
    - master
    - install
    - master_install

  roles:
    - role: ../
      task: master
      boss__nfs__master_node_ip: '192.168.50.101'
      boss__nfs__nfs_interface: 'enp0s8'
      # boss__nfs__nfs_interface: 'enp0s3'


- hosts: nodes
  name: (nodes) - Install and configure nfs
  gather_facts: True
  become: yes
  become_method: sudo
  environment:
    DEBIAN_FRONTEND: noninteractive
  vars:
    boss__ntp__timezone: 'America/New_York'
  tags:
    - nodes
    - install
    - master_install

  roles:
    - role: ../
      task: client
      boss__nfs__master_node_ip: '192.168.50.101'
      boss__nfs__nfs_interface: 'enp0s8'
      # boss__nfs__nfs_interface: 'enp0s3'

# # - hosts: client
# #   tasks:
# #   - name: Update fstab file
# #     lineinfile:
# #       path: /etc/fstab
# #       line: "172.32.0.184:/{{ volname }} /mnt/ontap nfs defaults 0 0"
# #   - name: Verify mount directory exists
# #     file:
# #       path: /mnt/ontap
# #       state: directory
# #   - name: Mount nfs export
# #     mount:
# #       state: "{{ state }}"
# #       path: /mnt/ontap
# #       src: "172.32.0.184:/{{ volname }}"
# #       fstype: nfs

- hosts: nodes
  name: (nodes) - Install and configure tmuxinator
  gather_facts: True
  become: no
  become_method: sudo
  vars:
    bossjones__user: vagrant
    bossjones__group: vagrant
  environment:
    DEBIAN_FRONTEND: noninteractive
  tags:
    - ruby
    - nodes
    - servers
    - rvm
    - install
    - node_install
  roles:
    - role: ../
      task: monitor
      boss__nfs__master_node_ip: '192.168.50.101'
      boss__nfs__nfs_interface: 'enp0s8'
