---
##############################################################################
# SERVERS: Install and configure ntp
##############################################################################
- hosts: masters
  name: (masters) - Install and configure nfs
  gather_facts: True
  become: yes
  become_method: sudo
  environment:
    DEBIAN_FRONTEND: noninteractive
  vars:
    boss__ntp__timezone: 'America/New_York'
  tags:
    - master
    - install
    - master_install

  roles:
    - role: ../
      boss__nfs__master_node_ip: '192.168.50.101'
      boss__nfs__nfs_interface: 'enp0s3'
