---
##############################################################################
# SERVERS: Install and configure ntp
##############################################################################
- hosts: servers
  name: (servers) - Install and configure ntp
  gather_facts: True
  become: yes
  become_method: sudo
  environment:
    DEBIAN_FRONTEND: noninteractive
  vars:
    boss__ntp__timezone: 'America/New_York'
  tags:
    - docker
    - docker-provision
    - worker
    - install
    - worker_install
    - ha
    - ntp
    - slow

  roles:
    - role: ../
      tags: [ 'worker', 'install', 'worker_install', 'ntp']
      task: prepare-ntpd
      boss__ntp__timezone: 'America/New_York'
      boss__kubernetes__kubeadm__master_node_ip: '192.168.1.241'
      boss__kubernetes__kubeadm__kubernetes_interface: 'enp0s3'
